### ISSUE TITLE
Calendar UI rendering problem while slide right and left inside the Fragment

### ISSUE THREAD

**Issue by kalaiarasisp** [yannecer/NCalendar#13]
The nCalendar working perfectly, when subclass extends in AppCompactActivity. It showing rendering problem when subclass extends Fragments. Please check and give solution.
<img width="341" alt="screen shot 2017-12-21 at 11 22 36 pm" src="https://user-images.githubusercontent.com/9463173/34268369-6e894ca4-e6a6-11e7-9b41-25ebe3f79f52.png">
<img width="322" alt="screen shot 2017-12-21 at 11 22 48 pm" src="https://user-images.githubusercontent.com/9463173/34268370-6ed02566-e6a6-11e7-9d5a-540f4a385f47.png">

**Comment by yannecer** [comment]
@kalaiarasisp I don't know how you use it.I have updated the code in the Fragment，you can refer to it. OR, show your code .

**Comment by kalaiarasisp** [comment]
Please check the attached file. 
[LeaveShiftFragment.txt](https://github.com/yannecer/NCalendar/files/1581557/LeaveShiftFragment.txt)

**Comment by yannecer** [comment]
@kalaiarasisp I tested it with your code , but I don't find this bug. Look at the latest code,please.
TestFragment

**Comment by kalaiarasisp** [comment]
Thank you so much. Issue fixed.

**Comment by showkiwi** [comment]
how you fixed this，i have the same problem

**Comment by kalaiarasisp** [comment]
Are you using fragment?
