### ISSUE TITLE
默认周日历时，手指放在 RecyclerView 区域内 向下滑，如何不让月日历展开，始终保持周日历显示

### ISSUE THREAD

**Issue by ChittyTina** [yannecer/NCalendar#16]
@yannecer  您好，请问：默认周日历时，手指放在 RecyclerView 区域内 向下滑，如何不让月日历展开，始终保持周日历显示？因为我的项目需求是 周日历，不需要月日历。谢谢～ 

P.S. 下图是用 非正式版 Vysor 映射的，所以界面内容不太清晰，望见谅～ 但是 滑动效果是可以看到的。

![ncalendar01](https://user-images.githubusercontent.com/13344960/34933065-70ff8a48-fa10-11e7-9545-e870d18033ca.gif)

**Comment by ChittyTina** [comment]
sorry ～ 我解决了。解决方法如下：
将 NCalendar.java 中 onNestedPreScroll() 方法中的 move(dy, true, consumed); 方法注释掉即可。

**Comment by yannecer** [comment]
@ChittyTina 不用这么麻烦，有提供单独的周日历的WeekCalendar

**Comment by ChittyTina** [comment]
好的，谢谢～

**Comment by yannecer** [comment]
@ChittyTina 不客气
