### ISSUE TITLE
添加下拉刷新

### ISSUE THREAD

**Issue by nemio77** [yannecer/NCalendar#21]
你好，我需要添加一个下拉刷新SwipeRefreshLayout，只有在月日历完全显示时下拉刷新可用，其他时候比如说转换成周日历的时候就不可用。月日历完全显示可以通过判断recyclerview在屏幕的位置判断，但是要监听什么控件的滑动来判断有什么建议么？

**Comment by yannecer** [comment]
@nemio77 这个，看一下是不是可以根据月周的状态判断SwipeRefreshLayout是否可用来，可能还会出现滑动冲突的情况，根据你的需求判断触摸事件的分发和拦截等，可以试一下

**Comment by nemio77** [comment]
十分感谢，在NCalendar类的move()方法里面判断即可

**Comment by troytian1986** [comment]
@nemio77 大拿，能讲详细点吗？我弄了半天没整出来。。。

**Comment by yannecer** [comment]
新版已支持
