### ISSUE TITLE
能否通过点击事件调出日历视图？

### ISSUE THREAD

**Issue by sendtion** [yannecer/NCalendar#22]
我不想默认就显示，想在用户点击按钮后显示出日历视图，这个该怎么操作？

**Comment by yannecer** [comment]
有提供方法getState()获取日历视图，在点击的回调里面调用这个方法即可

**Comment by sendtion** [comment]
@yannecer 我说的不是切换周视图和月视图哦，我的意思是默认不显示这个控件，不显示周视图也不显示月视图，当我点击按钮的时候，再显示日历视图，再点击按钮可以隐藏日历视图

**Comment by sendtion** [comment]
@yannecer 你说的getState()返回int值，只能判断当前是周视图还是月视图，并不是我想要的

**Comment by yannecer** [comment]
@sendtion setVisibility(View.VISIBLE)不可以吗，如果出现显示不正常，就延时100毫秒调用

**Comment by sendtion** [comment]
@yannecer 使用setVisibility岂不是把关联的RecyclerView列表也隐藏了？

**Comment by yannecer** [comment]
@sendtion 是的一起隐藏，感觉，你的这个需求，应该可以单独使用月日历或者周日历就可以了，有点不是太明白你的需求

**Comment by yannecer** [comment]
@sendtion 那我觉得你的需求，用弹窗更合适点
