### ISSUE TITLE
事件冲突这一块还没做好，还需要优化

### ISSUE THREAD

**Issue by twoways** [yannecer/NCalendar#29]
1、MIUI9 在RecyclerView内快速向上滑动并松开手指，在没有触发日历收缩的情况下，RecyclerView会继续向上滚动。
2、MIUI10 当NestedScrollView里面的内容超过一屏时，滑动变得不灵敏了。

**Comment by yannecer** [comment]
MIUI9的问题最新代码已修复，miui10的问题，我再看一下

**Comment by yannecer** [comment]
miui10 NestedScrollView划动卡顿的问题解决了
