### ISSUE TITLE
当前日期之后的日期能否设置成为不可点击并设置成为其他的颜色（eg：灰色等）？

### ISSUE THREAD

**Issue by wzhwcp** [yannecer/NCalendar#31]
如题所问

**Comment by yannecer** [comment]
@wzhwcp 后面更新了这个需求我再通知你

**Comment by yannecer** [comment]
更新了，设置区间，自定义属性 startDate  endDate设置日期， disabledAlphaColor设置颜色透明质，0-255，代码设置setDateInterval()

**Comment by threedeer** [comment]
你好，这些我都看了下，我现在还有个疑问，就是我的startDate是2020-01-01，结束日期是当前月的最后一天，比如2020-09-30，但是我希望我在2020-09-16之后的都不能点击，我设置了setDateInterval，
`LocalDate today = new LocalDate();
        // 获取Calendar
        Calendar cd = Calendar.getInstance();
// 设置时间,当前时间不用设置

// 设置日期为本月最大日期
        cd.set(Calendar.DATE, cd.getActualMaximum(Calendar.DATE));

// 打印
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");


        bindingView.mcCalendar.setDateInterval("2020-01-01", format.format(cd.getTime()), today.toString());`
16号之后依然是可以点击的，
如果在今日之前的某些日期，不允许点击的话应该怎?
