### ISSUE TITLE
希望下个版本优化，越来越好

### ISSUE THREAD

**Issue by DreamClimb** [yannecer/NCalendar#33]
周六、日的字体颜色是不能单独设置的。只能设置节假日的休或者班的字体颜色，(六、日)日期数字的颜色还是不能单独设置。希望日历背景可以设置图片或者颜色，目前只能设置颜色。目前已经接近完美了。哈哈，这个版本改的内容很多呀。高度封装。不错！

**Comment by yannecer** [comment]
已增加自定义绘制类CalendarPainter，可以自定义日历界面了
