### ISSUE TITLE
周日历显示错误

### ISSUE THREAD

**Issue by zlxxwl** [yannecer/NCalendar#35]
2019年第一周的日历显示错误。今天是1.3，星期四。显示的是1.3，星期五。
补充：不好意思，我看错了，你的周日历是从周日到周一显示的。我的界面是从周一到周日显示的。
补充：不好意思，我看错了，你的周日历是从周日到周一显示的。我的界面是从周一到周日显示的。

**Comment by yannecer** [comment]
@zlxxwl 日历里面有设置一周开始的是周一还是周日

**Comment by zlxxwl** [comment]
好的，谢谢。看到了
