### ISSUE TITLE
在折叠模式的时候，设置今天以前的日期文字颜色

### ISSUE THREAD

**Issue by zengcanxiang** [yannecer/NCalendar#39]
在周视图的时候，想要设置如果是今天以前的日期，是灰色，如果是今天及今天以后的日期的文字为黑色，似乎没有这个重载绘制的方法。

在BaseCalendarView 的onDraw 方法里。好像只有`isEqualsMonthOrWeek`判断条件。这个是判断当月的，但是，我像判断是当天以前的。

本来像用设置日期区间的方法，但是发现，设置区间之后，就不能滑动到区间前的日期了。

**Comment by yannecer** [comment]
@zengcanxiang 在onDraw 方法里面，可以根据具体的需求做些调整，可以再加一个判断条件，让当天以前的日期绘制灰色，之后的绘制黑色

**Comment by zengcanxiang** [comment]
@yannecer 复写onDraw是否有简便一些的方法。还是说，只能依赖源码来修改。

还有有个问题咨询一下，如果要使 日历不能使用滑动手势来切换月和周，只能通过按钮来切换，现在又这个属性么

**Comment by yannecer** [comment]
@zengcanxiang 重写不行，只能修改源码，因为现在项目的判断条件是固定的，需求需要增加新的判断条件，只能修改绘制逻辑，第二个问题，也需要修改NCalendar的源码，禁止NestedScrollingParent的嵌套滑动就可以了，onStartNestedScroll返回flase

**Comment by zengcanxiang** [comment]
@yannecer  谢谢解答。
