### ISSUE TITLE
左右快速滑动，及点击后 偶先界面异常

### ISSUE THREAD

**Issue by caizhibiao** [yannecer/NCalendar#4]
https://github.com/caizhibiao/respository
里面有个图片和mp4视频

**Comment by yannecer** [comment]
@caizhibiao 快速滑动偶尔出现的那个问题，我也有出现过，但是几率非常小，不能特定复现，没法调试，也就没有解决，点击错乱那个，提交上来的代码好像没有这个问题

**Comment by caizhibiao** [comment]
复现的步骤：月历滑动到一半，然后另一只手上滑下面的列表，就会出现上面那个bug和其他的显示问题

**Comment by yannecer** [comment]
@caizhibiao 你的是什么机器？是百分百复现吗？我的小米6没有这个bug

**Comment by caizhibiao** [comment]
note 3，必先的。 现在9月份，向左滑动一多半后，另一只手上滑下面的列表，再下拉成月视图，这个时候变成10月份的日期了，而最上面的月还是9月，仔细看看就知道了

**Comment by yannecer** [comment]
@caizhibiao 你加我qq吧，我依然没有复现
