### ISSUE TITLE
为什么选择一个日期后,翻页的时候其他月的这一天也会显示被选中?

### ISSUE THREAD

**Issue by whb7762300** [yannecer/NCalendar#5]
比如我选择了9月20号这一天,翻月的时候其他月份的20号也会显示被选中?周日历也有类似的问题,比如9月20号是星期二,周日历翻阅的时候每周的周二都显示被选中

**Comment by yannecer** [comment]
@whb7762300 仿miui的日历，需要选中日期来判断位置，现在更新了单一月日历和周日历默认不选中的设置

**Comment by whb7762300** [comment]
@yannecer 感谢

**Comment by yannecer** [comment]
@whb7762300 不客气
