### ISSUE TITLE
怎么添加已经点击的日期

### ISSUE THREAD

**Issue by Daydream9527** [yannecer/NCalendar#50]
你好，我想问一下要怎么实现把已经点击选择的日期，在日历再次出现的时候显示上去

**Comment by yannecer** [comment]
`
        List<LocalDate> allSelectDateList = monthCalendar.getAllSelectDateList();

        allSelectDateList.add(new LocalDate("2019-10-23"));
        allSelectDateList.add(new LocalDate("2019-10-24"));
        allSelectDateList.add(new LocalDate("2019-10-25"));
        allSelectDateList.add(new LocalDate("2019-10-26"));`
