### ISSUE TITLE
org.joda.time.IllegalInstantException: 

### ISSUE THREAD

**Issue by balajip-lab** [yannecer/NCalendar#51]
org.joda.time.IllegalInstantException: Cannot parse "2017-10-15": Illegal instant due to time zone offset transition (America/Sao_Paulo)

How to fix this issue? Can you please guide me asap.

**Comment by yannecer** [comment]
@balajip-lab Time zone, take a look at this project [https://github.com/JodaOrg/joda-time](url)

**Comment by balajip-lab** [comment]
I can't see anything in the above link 
![Screenshot 2019-10-08 at 3 13 33 PM](https://user-images.githubusercontent.com/52075170/66385537-46b83680-e9de-11e9-87b1-1393184a456e.png)

**Comment by balajip-lab** [comment]
Got it, Buddy. Thank you So much...

**Comment by sanjeevirajm** [comment]
@balajip-lab What did you got? I can't see anything
