### ISSUE TITLE
怎么实现竖直方向的日历呢？在切换日期的时候，怎么增加动画。从当前日期到目标日期？

### ISSUE THREAD

**Issue by threedeer** [yannecer/NCalendar#64]
怎么实现竖直方向的日历呢？在切换日期的时候，怎么增加动画。从当前日期到目标日期？

**Comment by yannecer** [comment]
@threedeer 日历是继承ViewPager，让日历继承一个竖直滑动的ViewPager就可以了，日历跳转动画也是ViewPager的翻页动画

**Comment by threedeer** [comment]
好的  多谢

**Comment by threedeer** [comment]
可以使用recyclerview替换viewpager吗？我们希望能实现像recyclerview那种滑动的样式，而不是每次滑动一个item

**Comment by threedeer** [comment]
我替换成recyclerview之后，数据量大的时候会特别卡，而且并没有显示数据。

**Comment by yannecer** [comment]
@threedeer 刚看到你的信息，如果想像RecyclerView那样滑动，可以使用自定义View，创建一个单页的日历View（库中有相关代码），RecyclerView的每个item都是这个View，再根据不同的月份，传值绘制即可

**Comment by threedeer** [comment]
多谢解答
