### ISSUE TITLE
月日日历翻页后无法点击

### ISSUE THREAD

**Issue by victorfan336** [yannecer/NCalendar#69]
场景：
当前月日到日历选中任何月份的x日（如7-07），然后翻页后的那个月份的x日（如8-07）竟然无法点击？为啥会选中呢（8-07）？日历的点击逻辑是，选中的那天无法点击，就直接导致我翻页后的x日也无法点击？
请问有啥解决办法吗？我看了下源码，没有找到解决方法，谢谢。
@yannecer

**Comment by yannecer** [comment]
你可以使用 默认不选中的模式

**Comment by yannecer** [comment]
SINGLE_DEFAULT_UNCHECKED
