### ISSUE TITLE
onCalendarChange自动执行三次

### ISSUE THREAD

**Issue by CharlesWWT** [yannecer/NCalendar#70]
给日历设置setOnCalendarChangedListener监听，打log onCalendarChange会自动执行三次 用的5.0.1版本

**Comment by CharlesWWT** [comment]
用4.3.0版本就没问题，只执行一次

**Comment by CharlesWWT** [comment]
4.4.1之后的版本都是自动执行三次

**Comment by yannecer** [comment]
@CharlesWWT 你看下demo，我打印log，日期变化是打印一次

**Comment by CharlesWWT** [comment]
![微信截图_20201205150913](https://user-images.githubusercontent.com/22735105/101236426-094b5800-370c-11eb-83ac-1e895b0b4569.png)
这个图就是我运行demo，刚打开页面的log，也是默认执行三次，应该和手机和都IDE无关，我试过换手机和用高版本ide了也是一样的效果

**Comment by yannecer** [comment]
@CharlesWWT 有修改库中代码吗，我打印的log是只执行一次，或者你进群来，私聊我一下

**Comment by yannecer** [comment]
@CharlesWWT 5.0.2版已修复
