### ISSUE TITLE
如何能支持选择1901之前的日期

### ISSUE THREAD

**Issue by HuangDayu** [yannecer/NCalendar#72]
新年好，如何能支持选择1901之前的日期，并且重新绘制日历ui中的背景，农历和周历信息。谢谢。

**Comment by HuangDayu** [comment]
附加一个问题，24节气算法存在问题，4月4号是清明，4月20号才是谷雨，明显是错误的，谷雨应该是4月19号。所以，24节气算法是错在问题的。建议提供一个实现农历信息的接口。

**Comment by yannecer** [comment]
@HuangDayu 可以修改源码中的日期限定条件，由于没有1901年之前的农历信息，所以代码中限制了1901这个时间，如果只展示1901年之前的公历，是可以的，

**Comment by HuangDayu** [comment]
> @HuangDayu 可以修改源码中的日期限定条件，由于没有1901年之前的农历信息，所以代码中限制了1901这个时间，如果只展示1901年之前的公历，是可以的，

建议框架可以提供一个重写农历信息的接口，可以通过超过日期限定的那个回调函数向框架提供农历和西历信息。

**Comment by yannecer** [comment]
@HuangDayu 有这个方法，InnerPainter的setReplaceLunarStrMap方法

**Comment by HuangDayu** [comment]
> @HuangDayu 有这个方法，InnerPainter的setReplaceLunarStrMap方法

好的
