### ISSUE TITLE
你好请问怎么设置日历的背景颜色NCalendar

### ISSUE THREAD

**Issue by clank520** [yannecer/NCalendar#8]

**Comment by clank520** [comment]
在MonthAdapter设置 nMonthView.setBackgroundResource(R.color.selectCircleColor);目前我是这样设置的，请问下还有单独的方法设置吗？

**Comment by yannecer** [comment]
@clank520 这个没有单独写设置的方法，在CalendarPager类的构造方法中，有一句setBackgroundColor(Color.WHITE);你改成你需要的颜色就可以了

**Comment by clank520** [comment]
@yannecer 我看了下在MonthCalendar中有个 monthcalendar.setDefaultSelect(false);的方法，在NCalendar这个里面有什么方法可以达到类似效果吗

**Comment by yannecer** [comment]
@clank520 不能，月周切换必须有选中的日期，月周切换不选中日历在逻辑上面有问题

**Comment by clank520** [comment]
@yannecer 我的意思如果我在选中了10.20号，当时在我滑动到9月的时候9月20号是被选中的，怎么不被选中。我看你在MonthCalendar中通过.setDefaultSelect(false)实现了，但是在ncalendar里面没有实现这个效果，想问下ncalendar这个View怎么实现类似效果

**Comment by yannecer** [comment]
@clank520 我明白你的意思，这种不选中的切换是有问题的，是逻辑方面的问题，不选中切换的情况，你仔细想一下就能明白，是没有基准点的，而且，周视图只显示一周，如果当月有选中的，但是当周没有选中的，回来切换还会出现是依有选中日期的周为准还是依上次没有选中的周为准的问题，就是逻辑上有点乱

**Comment by clank520** [comment]
@yannecer 懂了  谢谢你
