### ISSUE TITLE
NCalendar包裹RecyclerView上下滑动切换周、月日历时会抖动

### ISSUE THREAD

**Issue by shichunlei** [yannecer/NCalendar#9]
当NCalendar包裹RecyclerView时上下滑动切换周、月日历时RecyclerView页面部分会上下抖动一下，不知道有没有遇到这个问题。

布局代码：

        <com.necer.ncalendar.calendar.NCalendar
            android:id="@+id/ncalendar"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:backgroundColor="@color/colorPrimary"
            app:defaultCalendar="Week"
            app:firstDayOfWeek="Sunday"
            app:isShowHoliday="false">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recyclerview"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@color/white" />
        </com.necer.ncalendar.calendar.NCalendar>

**Comment by yannecer** [comment]
@shichunlei 你看一下demo又这个问题吗，我好像没有遇到

**Comment by yannecer** [comment]
@shichunlei 你看一下demo有这个问题吗，我好像没有遇到

**Comment by shichunlei** [comment]
建议单一月日历添加上翻页监听事件，因为当设置默认不选中时不能监听到滑动到哪个月了。

**Comment by yannecer** [comment]
@shichunlei 这个功能有啊，难道又出bug了。。。我到公司看一下再给你答复

**Comment by yannecer** [comment]
@shichunlei 我又看了一下你提得这个问题，默认不选中的时候，翻页之后当页页面是没有选中日期的，所以翻页才没有回调，整个默认不选中的日历回调的是选中的日期，翻页之后选中的还是之前的日期，所以翻页没有回调，如果你需要这个功能，改一下源码就可以了
